### ISSUE TITLE
Collapse navigation tree

### ISSUE THREAD

**Issue by benoit74** [openzim/devdocs#16]
When opening the ZIM, by default the navigation tree on the left is expanded, which does not help to grab the structure of the page / content.

![Screenshot 2024-09-10 at 09 30 45](https://github.com/user-attachments/assets/9c043319-1acb-4544-ab88-bc212ac098b9)

I know that CSS comes directly from devdocs, but this is not what happens on devdocs.io: https://devdocs.io/lua~5.4/ ; do we have a bug or something we could fix?

**Comment by josephlewis42** [comment]
Very interesting. The logic that expands the list tries to expand section(s) that link to the current page. In Lua's case there is only one page of content and the sections/links represent headings in that document. I see CoffeeScript is similarly set up, and parts of RequireJS are as well.

Because DevDocs treats the index page as a special case rather than including it in the navbar, I think we can also treat it as a special case in the v0.1.0 docs. I'm opening #24 with a proposed long term fix.
